### ISSUE TITLE
G4Region and step limit

### ISSUE THREAD

**Issue by ebrianne** [ClarkMcGrew/edep-sim#16]
Hi Clark,

Thanks for adding the feature of the step limit that was needed for the simulation in the gas TPC. I have a small question, 
do you think it would be better to implement this feature as a G4Region? 

Such example would be:
```cpp
G4Region* reg = G4RegionStore::GetInstance()->GetRegion(name);
G4UserLimits* limits = new G4UserLimits();
limits->SetMaxAllowedStep(2.0*CLHEP::mm);
reg->SetUserLimits(limits);
```

For now, the step limit auxiliary value is assigned to a specific volume in the gdml but daughter volumes don't get the step limit set up in that way.

**Comment by ClarkMcGrew** [comment]
Sorry for the lag, I managed to reset my "watch" for edep-sim.  

I didn't go down that route because I don't see any support regions in gdml, and I don't have any good ideas for adding a general interface. 

I guess the current "StepLimit" could be modified to create a new region, and add the current logical as the root volume.  I think that's a bit of a misuse of the G4Region, but the alternative is to predefine the regions someplace else in the code.

**Comment by ClarkMcGrew** [comment]
In practice this regions are not handled in GDML, and seem to require significant structural changes to add as an extension.  The same result can be achieved using the "StepLimit" auxtype for the logical volume.  It's not as convenient, but has been tested and works. (e.g. used in the DUNE ND SAND TPCs)
